version: "3.8"

services:
  web_app:
    build: .
    container_name: go_urlshortener
    image: go-urlshort:latest
    restart: always
    ports:
      - "3004:8080"
    command: go run main.go
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
    volumes:
      - ./:/go/src
    depends_on:
      - database

  database:
    container_name: go_urlshort_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=short_urls
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:

networks:
  default:
    external:
      name: myNetwork